### PR TITLE
php >= 8.0 compatibility

### PR DESCRIPTION
**Pull request by 8ctopus**
Thanks for a great logger that I just discovered when I was looking at monolog alternatives. As I'm going to use it on php 8.1, I've spent a few hours updating the whole project for that purpose.

Main changes:
- use psr/log 2 or 3
- use phpunit 8 or 9
- fix usort() returning bool from comparison function is deprecated
- update tests for phpunit 8/9
- update readme examples for php 8

### CODE REVIEW

**Comment by frqnck** [comment]
Hi @8ctopus,

Great stuff. We need Scrutiniser or similar back in order to automate testing all of this. Bit busy at the mo but once I have some bandwidth I will look into all this deeper in order to merge your contribution. Looks to me the move to PHP 8 grants a v2 release and keep v1 for PHP<8.

Please do not hesitate if you fancy getting the tests automation back in order.

 Thank you so much for you contribution.

**Comment by 8ctopus** [comment]
@frqnck would github workflows do? I've implemented it here as an example https://github.com/8ctopus/pigeon-invoice/blob/master/.github/workflows/ci.yaml

**Comment by frqnck** [comment]
Sure, although if you could do that in a separate PR/branch so both the current version and your version get supported that would be awesome.

**Comment by 8ctopus** [comment]
Franck, I've created a separated PR for the tests and merged them into this branch.
Tests passed on both php 8.0 and 8.1 https://github.com/8ctopus/log/runs/7524383334?check_suite_focus=true

**Comment by frqnck** [comment]
Hello @8ctopus This PR was merged too – thank you for the large contribution. This will be released as 1.3.0 once tested. F

**Pull request merged**
