### PR TITLE
Add minimum level logged

### PR DESCRIPTION
**Pull request by 8ctopus**
And here a way to get the minimum level that was logged. Here's how I use it:

```php
    foreach ($container['logger']->getBuckets() as $bucket) {
        // check not empty and at least warning (4)
        if (get_class($bucket) === 'Apix\\Log\\Logger\\File' && !$bucket->isEmpty() && $bucket->getMinLevelLogged() <= 4) {
            // get log content
            $content = file_get_contents($bucket->getDestination(), false);

            mail_log($content);
        }
    }
```

### CODE REVIEW

**Comment by 8ctopus** [comment]
Hello Franck, any chance for you to review the PRs? If you don't have the time for it, I will have to detach my fork.

**Comment by frqnck** [comment]
Hi @8ctopus, thanks for the contribution but we already have the same functionality in place. E.g. `$urgent_logger->setMinLevel('critical');   // catch logs >= to critical`.  Take a look at `->setMinLevel()` and associated. I will close this.

**Comment by 8ctopus** [comment]
Thank you Franck, you misunderstood the pull request's intent. The code in question allows the dev to see what was the worst level logged so you can for example decide to send the log by email if there was a log >= critical.

I use that feature to send an email to me when there was a problem worth my attention.

**Comment by frqnck** [comment]
Hi @8ctopus,

I understood your intention perfectly but you are abstracting away what’s already in this API.

For development purposes or not,  just use the [multiple log buckets dispatcher](https://github.com/apix/log#advanced-usage--multi-logs-dispatcher), e.g.

´´´php
$critical_logger = new Apix\Log\Logger\Mail('foo@bar.com');
$critical_logger->setMinLevel(‘critical');

$logger->add($critical_logger);  // inject this log bucket
´´´

**Comment by 8ctopus** [comment]
Correct me if I'm wrong, with my PR, it's possible to get this:

    [2023-01-19 15:10:01] INFO Running FR script in production on webch5...
    [2023-01-19 15:10:01] INFO process purchase email - test@gmail.com
    [2023-01-19 15:10:01] ERROR localizeCountry - FAILED - CONGO, THE DEMOCRATIC REPUBLIC OF THE

while without it, I would only get this:

    [2023-01-19 15:10:01] ERROR localizeCountry - FAILED - CONGO, THE DEMOCRATIC REPUBLIC OF THE

**Comment by 8ctopus** [comment]
Nevermind, I've detached the fork and will work on it on my side. Thank you for the work done.

**Pull request closed without merging**
