### PR TITLE
automated testing

### PR DESCRIPTION
**Pull request by 8ctopus**
Added github workflow for automated testing

### CODE REVIEW

**Comment by 8ctopus** [comment]
@frqnck Will you have time to review the changes?

**Comment by frqnck** [comment]
@8ctopus give me few days and I will. Just landed in France, and now in the midst of a family reunion w 50 folks..

**Comment by 8ctopus** [comment]
@frqnck Ah, je comprends, profitez bien.

**Comment by 8ctopus** [comment]
@frqnck Hello Franck, hope all is well, just a kind reminder, or otherwise I'll just detach the fork.

**Comment by frqnck** [comment]
Hello @8ctopus, sorry for that -- inundated with stuff. Will merge this now.

**Comment by 8ctopus** [comment]
All good, thank you for the merge.

**Pull request merged**
